#+BEGIN_HTML
---
layout: post
title: "今天你应当学习Emacs Lisp的5点理由"
date: 2013-05-03 18:12
comments: true
categories: 
---
#+END_HTML
* 前言
  Emacs Lisp是一种神秘莫测的黑客编程语言. 它的弱点是众所周知的, 它很慢, 它是单线程的, 同时它的变量是动态绑定的, 等等等等. 我当然还能继续说下去, 但这些不是主要目的. 尽管有这些看得见的弱点, 但Emacs Lisp仍然是github上最流行的lisp方言, 这一点有许多程序员对此发誓. 至于我, 能平均每天写50到100行之间的Emacs Lisp代码.

  当然, 我决定投资我的时间去学习它, 并且发现这样做了以后更加高兴. 我真的希望以后也能如此. 我所遇到的主要问题是劝阻我不要将时间投资到编程语言上. 但是现在, 我真的希望在多年前就能花时间去学习它.

  尽管遇到这样的问题, 又是什么使它如此的棒呢? 为什么任何人都应当学习Emacs Lisp呢?

  所以, 事不宜迟, 下面我就给出当今应当学习Emacs Lisp的5点理由:
* 学习任意数量的Emacs Lisp都会立即使你的生活变得更美好
  你学习到的东西能够立即改变你的生活, 不是从现在起一年, 不是毕业以后, 也不是当你的团队开始下一个项目时你才会使用到这门语言, 而是 *现在*!

  许多Lisp方言位于理论的范围内, 这很好, 也有它们的位置. 但是Emacs Lisp显得"更快更脏". Emacs Lisp是非常有实践性的, 它能帮助你解决你每天所遇到的问题.

  如果你不懂任何Emacs Lisp, 那么你的.emacs文件有可能充满了为了安装所需的包而复制粘贴的各种代码, 这很正常. 但问题是这会迅速的变得难看. 不久之后你的.emacs文件就会变得非常难以维护. 学习Emacs Lisp会使你的Emacs生活更有秩序.

  如果你需要获得关于Emacs的任何帮助, 很有可能帮助你的那个人将会带来一些Lisp代码. 你很难对他说"对不起, 我不懂任何elisp!" 在##emacs站点, 会一点Emacs Lisp能使你更好的融入社区.

  今天, 学习Emacs Lisp, 会使你的生活更美好.
* Emacs Lisp和Emacs是一个真正有趣的编程平台
  你并不一定要是一个狂热的Emacs党. 我想任何人都会同意Emacs是有趣的.

  
